application: bueysherpa
version: 1
runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /
  script: main.php

#- url: /stylesheets
#  static_dir: stylesheets

#- url: /(.*\.(gif|png|jpg))$
#  static_files: static/\1
#  upload: static/.*\.(gif|png|jpg)$

#- url: /admin/.*
#  script: admin.app
#  login: admin

#- url: /.*
#  script: not_found.app
